repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff-check
        args: [--fix, --cache-dir, python/.ruff_cache]
        files: ^python/
      - id: ruff-format
        args: [--cache-dir, python/.ruff_cache]
        files: ^python/
